version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: nirikshan-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nirikshan
    volumes:
      - mongo_data:/data/db

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: nirikshan-ai-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nirikshan-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/nirikshan
      - AI_SERVICE_URL=http://ai-service:8000
      - JWT_SECRET=nirikshan_secret_key_2026
    depends_on:
      - mongodb
      - ai-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nirikshan-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
